worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

jwt_secret_key: CHANGE_ME
postgres-dsn: postgresql://postgres:postgres@localhost:5432/postgres
mongo-dsn: mongodb://mongo:mongo@localhost:27017/file_storage_mongo?authSource=admin